# PowerShell script to delete unused images from /public and /public/images
Remove-Item -Force "public/college-logo.png"
Remove-Item -Force "public/correspondent1.png"
Remove-Item -Force "public/generic-placeholder-icon.png"
Remove-Item -Force "public/placeholder-logo.png"
Remove-Item -Force "public/placeholder-logo.svg"
Remove-Item -Force "public/placeholder-user.jpg"
Remove-Item -Force "public/placeholder.jpg"
Remove-Item -Force "public/images/events-banner.png"
Remove-Item -Force "public/images/patrons-banner.png"
